// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7GELq26yne_BGmhmPZwz0uMTevx7MBg',
    appId: '1:489789081943:web:e51ab13792474b8f42d612',
    messagingSenderId: '489789081943',
    projectId: 'gelirgidertakip-40446',
    authDomain: 'gelirgidertakip-40446.firebaseapp.com',
    storageBucket: 'gelirgidertakip-40446.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnPXHPM8AhFiNvn8_P-1OnM5JId3wOp0',
    appId: '1:489789081943:android:0001082a4a8bf18e42d612',
    messagingSenderId: '489789081943',
    projectId: 'gelirgidertakip-40446',
    storageBucket: 'gelirgidertakip-40446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdmWN_Z8QTd-Mebd4HvcftceB1td249M',
    appId: '1:489789081943:ios:0ffb94121b0280e042d612',
    messagingSenderId: '489789081943',
    projectId: 'gelirgidertakip-40446',
    storageBucket: 'gelirgidertakip-40446.appspot.com',
    iosClientId: '489789081943-e77tu639ap0on6mf7eo25kcrj0f5tal0.apps.googleusercontent.com',
    iosBundleId: 'com.serhatgun.gelirgidertakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbdmWN_Z8QTd-Mebd4HvcftceB1td249M',
    appId: '1:489789081943:ios:0ffb94121b0280e042d612',
    messagingSenderId: '489789081943',
    projectId: 'gelirgidertakip-40446',
    storageBucket: 'gelirgidertakip-40446.appspot.com',
    iosClientId: '489789081943-e77tu639ap0on6mf7eo25kcrj0f5tal0.apps.googleusercontent.com',
    iosBundleId: 'com.serhatgun.gelirgidertakip',
  );
}
